### PR TITLE
Respond full user list if authorization is disabled

### LINKED ISSUE #191: /api/user-list doesn't work
Instead of returning a list of every user on the server, it returns an empty array.

### PR DESCRIPTION
**Pull request by towerofnix**
Fixes #191.

It turns out we weren't checking for authorization properly, so the "else" block wasn't being activated. And there was a typo in `runIfCondition` preventing "else" blocks from working, anyways; that's fixed as well.

@heyitsmeuralex I marked this semver: patch, but I'm not actually experienced with semantic versioning; is that right?

### CODE REVIEW

File: packages/server/api.js [hunk 1]
```diff
@@ -341,7 +341,7 @@ module.exports = async function attachAPI(app, {wss, db, dbDir}) {
         }
       }).concat(runIfNot.map(callback => async (request, response, next) => {
         if (!await conditionFn()) {
-          callback(request, rseponse, next)
```
Comment (heyitsmeuralex) [inline packages/server/api.js]: gotta love js

File: packages/server/api.js [hunk 2]
```diff
@@ -1225,7 +1225,7 @@ module.exports = async function attachAPI(app, {wss, db, dbDir}) {
   ])
 
   app.get('/api/user-list', [
-    ...middleware.runIfCondition(() => shouldUseAuthorization, [
+    ...middleware.runIfCondition(() => shouldUseAuthorization(), [
```
Comment (heyitsmeuralex) [inline packages/server/api.js]: ditto

**Comment by heyitsmeuralex** [comment]
As far as I can tell this should be patch.

Quick rundown:
* patch is for non-breaking patches that make the server follow the spec better
* minor is for backwards-compatible changes that don't fall under patch
* major is for breaking changes
